Default: &defaults
  database: yesod-full-sample.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-full-sample_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-full-sample_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-full-sample_production.sqlite3
  poolsize: 100
  <<: *defaults
